apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springboot-app2
  template:
    metadata:
      labels:
        app: springboot-app2
    spec:
      containers:
      - name: my-springboot-app2
        image: 312272890910.dkr.ecr.ap-south-2.amazonaws.com/my-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app2
spec:
  ports:
  - name: http
    port: 8085
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: springboot-app2
